apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-c
        image: nginx
        ports:
        - containerPort: 80
