apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ak
  name: ak
spec:
  containers:
  - image: httpd
    name: ak
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
