apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: xyz
  name: xyz
spec:
  containers:
  - image: nginx
    name: xyz
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
