apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  labels:
    name: pvc-pod
spec:
  containers:
  - name: pvc-pod
    image: httpd
    ports:
     - containerPort: 80
    volumeMounts:
      - mountPath: /var/www/html/
        name: mypvcxyz
  volumes:
    - name: mypvcxyz
      persistentVolumeClaim:
        claimName: mypvc
